const fs = require('fs');
const file = 'index.html';
let html = fs.readFileSync(file, 'utf8');

const FN_START = 'function buildPosterHtml(name, posText, tournamentName, photoUri, ratingPoints, stripLabel) {';
const FN_END   = '\r\n}\r\n\r\n// ── Rating Achieved poster';
const fnStart = html.indexOf(FN_START);
const fnEnd   = html.indexOf(FN_END) + 5;
if (fnStart === -1 || fnEnd < 1) { console.error('Function not found'); process.exit(1); }

// Write the new function as a plain string (no template literals to avoid newline issues)
const lines = [
'function buildPosterHtml(name, posText, tournamentName, photoUri, ratingPoints, stripLabel) {',
'  var base  = currentColor;',
'  var strip = darkenColor(base, 0.28);',
'  var bg    = lightenColor(base, 0.60);',
'  var stripWords = stripLabel ? stripLabel.split(" ") : (ratingPoints !== null ? ["RATING","GAINED"] : null);',
'  var twoCol = stripWords !== null;',
'  var isAchieved = stripLabel === "RATING ACHIEVED";',
'  var isGained   = ratingPoints !== null && !isAchieved;',
'',
'  var nameParts = name.trim().split(" ");',
'  var fn1 = escHtml((nameParts[0]||name).toUpperCase());',
'  var fn2 = nameParts.length > 1 ? escHtml(nameParts.slice(1).join(" ").toUpperCase()) : "";',
'  var nameDisplay = fn2 ? fn1+"<br>"+fn2 : fn1;',
'',
'  var css = ""',
'    +"* { margin:0; padding:0; box-sizing:border-box; }"',
'    +"body { background:#d8cfc3; display:flex; justify-content:center; padding-top:60px; font-family:Arial,sans-serif; }"',
'    +".toolbar { position:fixed; top:0; left:0; right:0; background:#fff; padding:8px 16px;"',
'    +"  display:flex; align-items:center; gap:10px; z-index:200; flex-wrap:wrap;"',
'    +"  box-shadow:0 2px 10px rgba(0,0,0,0.12); font-family:Arial,sans-serif; }"',
'    +".toolbar label { font-size:11px; color:#888; font-weight:600; margin-right:2px; }"',
'    +".toolbar input { border:1px solid #ddd; border-radius:5px; padding:5px 8px; font-size:12px; color:#222; outline:none; }"',
'    +".toolbar input:focus { border-color:#2196F3; }"',
'    +".t-name { width:160px; } .t-tourn { width:190px; } .t-result { width:110px; }"',
'    +".dl-btn { background:#9a7810; color:#fff; border:none; border-radius:6px; margin-left:auto;"',
'    +"  padding:7px 18px; font-size:13px; font-weight:700; cursor:pointer; white-space:nowrap; }"',
'    +".poster {"',
'    +"  width:540px; height:700px; position:relative; overflow:hidden;"',
'    +"  background-color:"+bg+";"',
'    +"  background-image:radial-gradient(circle,rgba(100,180,140,0.42) 2.5px,transparent 2.5px);"',
'    +"  background-size:24px 24px; font-family:Arial,Helvetica,sans-serif;"',
'    +"  box-shadow:0 8px 32px rgba(0,0,0,.25); }"',
'    +".strip {"',
'    +"  position:absolute; left:50px; top:55px; width:190px; height:590px;"',
'    +"  background:"+strip+";"',
'    +"  border-top-left-radius:65px; border-bottom-left-radius:65px; z-index:2; }"',
'    +(twoCol',
'      ?".champ-text { position:absolute; right:300px; top:55px; width:190px; height:420px;"',
'       +"  display:flex; flex-direction:row; align-items:flex-start; justify-content:center;"',
'       +"  padding-top:18px; gap:0; z-index:5; }"',
'       +".champ-text span { writing-mode:vertical-rl; text-orientation:mixed; transform:rotate(180deg);"',
'       +"  font-weight:900; font-family:\\"Arial Black\\",Arial,sans-serif;"',
'       +"  color:transparent; -webkit-text-stroke:4px #ffffff; letter-spacing:4px; white-space:nowrap; }"',
'       +".champ-text span:first-child { font-size:76px; margin-right:-10px; }"',
'       +".champ-text span:last-child { font-size:"+(isAchieved?"68":"78")+"px; }"',
'      :".champ-text { position:absolute; right:300px; top:55px; writing-mode:vertical-rl;"',
'       +"  text-orientation:mixed; transform:rotate(180deg); font-size:105px; font-weight:900;"',
'       +"  font-family:\\"Arial Black\\",Arial,sans-serif; color:transparent;"',
'       +"  -webkit-text-stroke:5px #ffffff; letter-spacing:0; white-space:nowrap; z-index:5; }"',
'    )',
'    +".medal { position:absolute; top:-1px; left:-40px; width:140px; z-index:1; pointer-events:none; }"',
'    +".profile { position:absolute; left:50px; bottom:10px; width:190px; height:190px;"',
'    +"  border-radius:50%; overflow:hidden; background:#aaa; border:4px solid #fff; z-index:10; }"',
'    +".profile img { width:100%; height:100%; object-fit:cover; display:block; }"',
'    +".grid-panel { position:absolute; left:238px; top:55px; width:302px; height:590px;"',
'    +"  background:#fff; z-index:2; border:1.5px solid #c0c0c0;"',
'    +"  box-shadow:-5px 0 16px rgba(0,0,0,.13),5px 5px 16px rgba(0,0,0,.09);"',
'    +"  display:flex; flex-direction:column; padding:10px 14px 10px 14px; }"',
'    +".logo-area { text-align:center; flex-shrink:0; }"',
'    +".logo-area img { width:180px; height:100px; object-fit:contain; display:inline-block; }"',
'    +".student-name { margin-top:6px; text-align:left;"',
'    +"  font-family:Georgia,serif; font-size:30px; font-weight:900; color:#2c3e50;"',
'    +"  text-transform:uppercase; line-height:1.2; flex-shrink:0; }"',
'    +".div1 { margin-top:8px; height:2.5px; background:"+strip+"; flex-shrink:0; }"',
'    +".ach-pos { margin-top:15px; text-align:left; font-size:18px; font-weight:700; color:#3a4a5c; line-height:1.5; flex-shrink:0; }"',
'    +".ach-tourn { margin-top:10px; text-align:left; font-size:16px; font-weight:600; color:#2c3e50; line-height:1.5; flex-shrink:0; }"',
'    +".rating-pill-wrap { margin-top:8px; display:flex; align-items:center; gap:14px; flex-shrink:0; }"',
'    +".rating-pill { background:#2196F3; color:#fff; border-radius:10px; padding:8px 18px; font-size:24px; font-weight:900; min-width:108px; text-align:center; flex-shrink:0; }"',
'    +".points-lbl { font-size:13px; font-weight:900; color:#1a2a3a; line-height:1.5; }"',
'    +".r-dot-div { margin-top:10px; border-top:1.5px dashed #b0c8d4; flex-shrink:0; }"',
'    +".div2 { margin-top:20px; height:2px; background:"+strip+"; opacity:0.45; flex-shrink:0; }"',
'    +".badge-row { margin-top:10px; display:flex; align-items:flex-start; gap:0; flex-shrink:0; }"',
'    +".badge-icon { width:50px; height:50px; object-fit:contain; object-position:left center; flex-shrink:0; margin-left:-5px; margin-right:-12px; }"',
'    +".badge-txt { font-size:15px; font-weight:600; color:#1565C0; line-height:1.25; font-family:\\"Arial Black\\",Arial,sans-serif; letter-spacing:0.5px; white-space:nowrap; }"',
'    +".proud-line { margin-top:15px; display:flex; align-items:center; gap:8px; flex-shrink:0;"',
'    +"  border:1.5px solid #e53935; border-radius:20px; padding:5px 8px; }"',
'    +".csoc-circle { width:26px; height:26px; border-radius:50%; object-fit:cover; flex-shrink:0; }"',
'    +".proud-txt { font-size:8.5px; font-weight:800; color:#0a1825; font-family:Arial,sans-serif; white-space:nowrap; }"',
'    +".proud-txt .c-red { color:#b83030; }"',
'    +".chess { position:absolute; bottom:-145px; right:-120px; width:360px; height:450px; z-index:10; object-fit:contain; }";',
'',
'  var sc = [',
'    "var BG=\\""+bg+"\\",ST=\\""+strip+"\\",RT="+(ratingPoints!==null?("\\""+ratingPoints+"\\""):"null")',
'      +",SW="+JSON.stringify(stripWords)+",SL="+(stripLabel?("\\""+stripLabel+"\\""):"null")+";",',
'    "function wT(c,t,x,y,mw,lh){var ws=t.split(\\\" \\\"),ln=\\\"\\\";for(var i=0;i<ws.length;i++){var ts=ln?ln+\\\" \\\"+ws[i]:ws[i];if(c.measureText(ts).width>mw&&ln){c.fillText(ln,x,y);ln=ws[i];y+=lh;}else ln=ts;}if(ln)c.fillText(ln,x,y);return y;}",',
'    "function dlPNG(){",',
'    "  var W=540,H=700,cv=document.createElement(\\"canvas\\");cv.width=W;cv.height=H;",',
'    "  var ctx=cv.getContext(\\"2d\\");",',
'    "  var md=document.querySelector(\\".medal\\"),ch=document.querySelector(\\".chess\\"),lg=document.querySelector(\\".logo-area img\\"),pf=document.querySelector(\\".profile img\\"),cs=document.querySelector(\\".csoc-circle\\");",',
'    "  ctx.fillStyle=BG;ctx.fillRect(0,0,W,H);",',
'    "  ctx.fillStyle=\\"rgba(100,180,140,0.42)\\";",',
'    "  for(var dy=12;dy<H;dy+=24)for(var dx=12;dx<W;dx+=24){ctx.beginPath();ctx.arc(dx,dy,2.5,0,Math.PI*2);ctx.fill();}",',
'    "  var sx=50,sy=55,sw2=190,sh=590,sr=65;",',
'    "  ctx.beginPath();ctx.moveTo(sx+sr,sy);ctx.lineTo(sx+sw2,sy);ctx.lineTo(sx+sw2,sy+sh);ctx.lineTo(sx+sr,sy+sh);ctx.quadraticCurveTo(sx,sy+sh,sx,sy+sh-sr);ctx.lineTo(sx,sy+sr);ctx.quadraticCurveTo(sx,sy,sx+sr,sy);ctx.closePath();ctx.fillStyle=ST;ctx.fill();",',
'    "  if(SW){",',
'    "    var s1=SW[0].split(\\"\\").reverse(),s2=(SW[1]||\\"\\\").split(\\"\\").reverse();",',
'    "    var fz1=76,fz2=(SL===\\"RATING ACHIEVED\\"?68:78);",',
'    "    var c1=sx+60,c2=sx+130;",',
'    "    ctx.strokeStyle=\\"rgba(255,255,255,0.9)\\";ctx.textAlign=\\"center\\";ctx.textBaseline=\\"middle\\";",',
'    "    ctx.font=\\"900 \\"+fz1+\\"px Arial,sans-serif\\";ctx.lineWidth=4;",',
'    "    for(var i=0;i<s1.length;i++){ctx.save();ctx.translate(c1,sy+18+fz1/2+i*fz1);ctx.rotate(-Math.PI/2);ctx.strokeText(s1[i],0,0);ctx.restore();}",',
'    "    ctx.font=\\"900 \\"+fz2+\\"px Arial,sans-serif\\";",',
'    "    for(var j=0;j<s2.length;j++){ctx.save();ctx.translate(c2,sy+18+fz2/2+j*fz2);ctx.rotate(-Math.PI/2);ctx.strokeText(s2[j],0,0);ctx.restore();}",',
'    "  }else{",',
'    "    var chs=[\\"P\\",\\"M\\",\\"A\\",\\"H\\",\\"C\\"];ctx.font=\\"900 105px Arial,sans-serif\\";ctx.strokeStyle=\\"#fff\\";ctx.lineWidth=5;ctx.textAlign=\\"center\\";ctx.textBaseline=\\"middle\\";",',
'    "    for(var k=0;k<chs.length;k++){ctx.save();ctx.translate(sx+95,sy+52+k*105);ctx.rotate(-Math.PI/2);ctx.strokeText(chs[k],0,0);ctx.restore();}",',
'    "  }",',
'    "  var px=238,py=55,pw=302,ph=590;",',
'    "  ctx.save();ctx.shadowColor=\\"rgba(0,0,0,0.13)\\";ctx.shadowBlur=16;ctx.shadowOffsetX=-5;ctx.shadowOffsetY=4;ctx.fillStyle=\\"#fff\\";ctx.fillRect(px,py,pw,ph);ctx.restore();",',
'    "  ctx.strokeStyle=\\"#c0c0c0\\";ctx.lineWidth=1;ctx.strokeRect(px,py,pw,ph);",',
'    "  var nmEl=document.querySelector(\\".student-name\\");",',
'    "  var nmLines=nmEl.innerText.trim().toUpperCase().split(\\"\\\\n\\");",',
'    "  ctx.fillStyle=\\"#2c3e50\\";ctx.font=\\"900 30px Georgia,serif\\";ctx.textAlign=\\"left\\";ctx.textBaseline=\\"alphabetic\\";",',
'    "  var nY=py+110+8+36;",',
'    "  ctx.fillText(nmLines[0]||\\"\\\",px+14,nY);",',
'    "  if(nmLines[1]){nY+=36;ctx.fillText(nmLines[1].trim(),px+14,nY);}",',
'    "  var d1Y=nY+8;ctx.fillStyle=ST;ctx.fillRect(px+14,d1Y,pw-28,2.5);",',
'    "  var cY=d1Y+2.5;",',
'    "  if(SL===\\"RATING ACHIEVED\\"){",',
'    "    cY+=10;",',
'    "    ctx.fillStyle=\\"#1565C0\\";ctx.font=\\"900 15px Arial,sans-serif\\";ctx.textAlign=\\"left\\";ctx.textBaseline=\\"alphabetic\\";",',
'    "    ctx.fillText(\\"ACHIEVED INTERNATIONAL\\",px+44,cY+18);ctx.fillText(\\"FIDE RATING\\",px+44,cY+18+19);",',
'    "    cY+=60;",',
'    "    var pe=document.querySelector(\\".ach-pos\\");if(pe){ctx.fillStyle=\\"#3a4a5c\\";ctx.font=\\"700 18px Arial,sans-serif\\";ctx.fillText(pe.textContent.trim(),px+14,cY+18);cY+=28;}",',
'    "    cY+=20;",',
'    "  }else if(RT){",',
'    "    cY+=8;var rpX=px+14,rpY=cY,rpW=108,rpH=48,rpRad=10;",',
'    "    ctx.save();ctx.shadowColor=\\"transparent\\";ctx.fillStyle=\\"#2196F3\\";",',
'    "    ctx.beginPath();ctx.moveTo(rpX+rpRad,rpY);ctx.lineTo(rpX+rpW-rpRad,rpY);ctx.quadraticCurveTo(rpX+rpW,rpY,rpX+rpW,rpY+rpRad);ctx.lineTo(rpX+rpW,rpY+rpH-rpRad);ctx.quadraticCurveTo(rpX+rpW,rpY+rpH,rpX+rpW-rpRad,rpY+rpH);ctx.lineTo(rpX+rpRad,rpY+rpH);ctx.quadraticCurveTo(rpX,rpY+rpH,rpX,rpY+rpH-rpRad);ctx.lineTo(rpX,rpY+rpRad);ctx.quadraticCurveTo(rpX,rpY,rpX+rpRad,rpY);ctx.closePath();ctx.fill();ctx.restore();",',
'    "    ctx.fillStyle=\\"#fff\\";ctx.font=\\"900 24px Arial,sans-serif\\";ctx.textAlign=\\"center\\";ctx.textBaseline=\\"middle\\";ctx.fillText(RT,rpX+rpW/2,rpY+rpH/2);",',
'    "    ctx.fillStyle=\\"#1a2a3a\\";ctx.font=\\"900 13px Arial,sans-serif\\";ctx.textAlign=\\"left\\";ctx.fillText(\\"POINTS\\",rpX+rpW+14,rpY+rpH/2-9);ctx.fillText(\\"GAINED\\",rpX+rpW+14,rpY+rpH/2+9);",',
'    "    cY+=rpH+10;ctx.save();ctx.setLineDash([4,4]);ctx.strokeStyle=\\"#b0c8d4\\";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(px+14,cY);ctx.lineTo(px+pw-14,cY);ctx.stroke();ctx.restore();",',
'    "    cY+=10;var te=document.querySelector(\\".ach-tourn\\");if(te){ctx.fillStyle=\\"#2c3e50\\";ctx.font=\\"600 16px Arial,sans-serif\\";ctx.textAlign=\\"left\\";ctx.textBaseline=\\"alphabetic\\";cY=wT(ctx,te.textContent.trim(),px+14,cY+16,pw-28,20)+6;}",',
'    "    cY+=20;",',
'    "  }else{",',
'    "    cY+=15;var pe2=document.querySelector(\\".ach-pos\\");if(pe2){ctx.fillStyle=\\"#3a4a5c\\";ctx.font=\\"700 18px Arial,sans-serif\\";ctx.textAlign=\\"left\\";ctx.textBaseline=\\"alphabetic\\";ctx.fillText(pe2.textContent.trim(),px+14,cY+18);cY+=28;}",',
'    "    var te2=document.querySelector(\\".ach-tourn\\");if(te2){ctx.fillStyle=\\"#2c3e50\\";ctx.font=\\"600 16px Arial,sans-serif\\";ctx.fillText(te2.textContent.trim(),px+14,cY+16);cY+=26;}",',
'    "    cY+=10;",',
'    "  }",',
'    "  ctx.fillStyle=ST;ctx.globalAlpha=0.45;ctx.fillRect(px+14,cY,pw-28,2);ctx.globalAlpha=1;cY+=2;",',
'    "  var plY=cY+20,plX=px+10,plW=pw-20,plH=36,plR=18;",',
'    "  ctx.save();ctx.strokeStyle=\\"#e53935\\";ctx.lineWidth=1.5;ctx.beginPath();",',
'    "  ctx.moveTo(plX+plR,plY);ctx.lineTo(plX+plW-plR,plY);ctx.quadraticCurveTo(plX+plW,plY,plX+plW,plY+plR);",',
'    "  ctx.lineTo(plX+plW,plY+plH-plR);ctx.quadraticCurveTo(plX+plW,plY+plH,plX+plW-plR,plY+plH);",',
'    "  ctx.lineTo(plX+plR,plY+plH);ctx.quadraticCurveTo(plX,plY+plH,plX,plY+plH-plR);",',
'    "  ctx.lineTo(plX,plY+plR);ctx.quadraticCurveTo(plX,plY,plX+plR,plY);ctx.closePath();ctx.stroke();ctx.restore();",',
'    "  ctx.font=\\"800 8.5px Arial,sans-serif\\";ctx.textBaseline=\\"middle\\";ctx.textAlign=\\"left\\";",',
'    "  var pl1=\\"PROUD \\",pl2=\\"CAISSA SCHOOL OF CHESS\\",pl3=\\" STUDENT\\",tX=plX+36,tY=plY+plH/2;",',
'    "  var w1=ctx.measureText(pl1).width,w2=ctx.measureText(pl2).width;",',
'    "  ctx.fillStyle=\\"#0a1825\\";ctx.fillText(pl1,tX,tY);ctx.fillStyle=\\"#b83030\\";ctx.fillText(pl2,tX+w1,tY);ctx.fillStyle=\\"#0a1825\\";ctx.fillText(pl3,tX+w1+w2,tY);",',
'    "  var fn2=(nmLines[0]||\\"poster\\").replace(/[^a-zA-Z0-9]/g,\\"_\\")+\\"_poster.png\\";",',
'    "  var tot=4,dn=0;",',
'    "  function fin(){var a=document.createElement(\\"a\\");a.download=fn2;a.href=cv.toDataURL(\\"image/png\\");document.body.appendChild(a);a.click();document.body.removeChild(a);}",',
'    "  function od(){if(++dn===tot)fin();}",',
'    "  function di(img,dx,dy,dw,dh){if(!img||!img.src){od();return;}var i2=new Image();i2.onload=function(){ctx.drawImage(i2,dx,dy,dw,dh);od();};i2.onerror=od;i2.src=img.src;}",',
'    "  function dc(img,cx,cy,cr){if(!img||!img.src){od();return;}var i2=new Image();i2.onload=function(){ctx.save();ctx.beginPath();ctx.arc(cx,cy,cr,0,Math.PI*2);ctx.clip();ctx.drawImage(i2,cx-cr,cy-cr,cr*2,cr*2);ctx.restore();ctx.beginPath();ctx.arc(cx,cy,cr,0,Math.PI*2);ctx.strokeStyle=\\"#fff\\";ctx.lineWidth=4;ctx.stroke();od();};i2.onerror=od;i2.src=img.src;}",',
'    "  function dcs(img,cx,cy,cr){if(!img||!img.src){od();return;}var i2=new Image();i2.onload=function(){ctx.save();ctx.beginPath();ctx.arc(cx,cy,cr,0,Math.PI*2);ctx.clip();ctx.drawImage(i2,cx-cr,cy-cr,cr*2,cr*2);ctx.restore();od();};i2.onerror=od;i2.src=img.src;}",',
'    "  di(md,-40,-1,140,220);",',
'    "  di(ch,300,395,360,450);",',
'    "  di(lg,px+(pw-180)/2,py+10,180,100);",',
'    "  dc(pf,145,595,95);",',
'    "  dcs(cs,plX+18,plY+plH/2,13);",',
'    "}",',
'  ].join("\\n");',
'',
'  var body = ""',
'    +"<div class=\\"poster\\">"',
'    +"  <img class=\\"medal\\" src=\\""+MEDAL_B64+"\\" alt=\\"\\">"',
'    +"  <div class=\\"strip\\"></div>"',
'    +(twoCol',
'      ?"  <div class=\\"champ-text\\"><span>"+(stripWords[0]||"")+"</span><span"+(isGained?" class=\\"gained\\"":"")+">"+(stripWords[1]||"")+"</span></div>"',
'      :"  <div class=\\"champ-text\\">CHAMP</div>"',
'    )',
'    +(photoUri?"  <div class=\\"profile\\"><img src=\\""+photoUri+"\\" alt=\\"\\"\\"></div>":"  <div class=\\"profile\\"></div>")',
'    +"  <div class=\\"grid-panel\\">"',
'    +"    <div class=\\"logo-area\\"><img src=\\""+LOGO_B64+"\\" alt=\\"CircleChess\\"></div>"',
'    +"    <div class=\\"student-name\\">"+nameDisplay+"</div>"',
'    +"    <div class=\\"div1\\"></div>"',
'    +(isAchieved',
'      ?"    <div class=\\"badge-row\\"><img src=\\""+BADGE_B64+"\\" class=\\"badge-icon\\" alt=\\"\\"><span class=\\"badge-txt\\">ACHIEVED INTERNATIONAL<br>FIDE RATING</span></div>"',
'       +"    <div class=\\"ach-pos\\">"+escHtml(posText)+"</div>"',
'       +"    <div class=\\"div2\\"></div>"',
'      :isGained',
'      ?"    <div class=\\"rating-pill-wrap\\"><div class=\\"rating-pill\\">"+ratingPoints+"</div><div class=\\"points-lbl\\">POINTS<br>GAINED</div></div>"',
'       +"    <div class=\\"r-dot-div\\"></div>"',
'       +"    <div class=\\"ach-tourn\\">"+escHtml(tournamentName)+"</div>"',
'       +"    <div class=\\"div2\\"></div>"',
'      :"    <div class=\\"ach-pos\\">"+escHtml(posText)+"</div>"',
'       +(tournamentName?"    <div class=\\"ach-tourn\\">"+escHtml(tournamentName)+"</div>":"")',
'       +"    <div class=\\"div2\\"></div>"',
'    )',
'    +"    <div class=\\"proud-line\\"><img src=\\""+CSOC_B64+"\\" class=\\"csoc-circle\\" alt=\\"\\"><span class=\\"proud-txt\\">PROUD <span class=\\"c-red\\">CAISSA SCHOOL OF CHESS</span> STUDENT</span></div>"',
'    +"  </div>"',
'    +"  <img class=\\"chess\\" src=\\""+CHESS_B64+"\\" alt=\\"\\">"',
'    +"</div>";',
'',
'  return "<!DOCTYPE html><html lang=\\"en\\"><head><meta charset=\\"UTF-8\\"><title>Poster</title><style>"+css+"</style></head>"',
'    +"<body>"',
'    +"<div class=\\"toolbar\\">"',
'    +"  <label>Name</label><input class=\\"t-name\\" id=\\"e-name\\" value=\\""+escHtml(name)+"\\" oninput=\\"updName(this.value)\\">"',
'    +"  <label>Result</label><input class=\\"t-result\\" id=\\"e-result\\" value=\\""+escHtml(posText)+"\\" oninput=\\"updResult(this.value)\\">"',
'    +(tournamentName!==""?"  <label>Tournament</label><input class=\\"t-tourn\\" id=\\"e-tourn\\" value=\\""+escHtml(tournamentName)+"\\" oninput=\\"updTourn(this.value)\\">":"")',
'    +"  <button class=\\"dl-btn\\" onclick=\\"dlPNG()\\">&#11015; Download PNG</button>"',
'    +"</div>"',
'    +body',
'    +"<"+"script>"',
'    +sc',
'    +"function updName(v){var el=document.querySelector(\\".student-name\\");if(el){var p=v.trim().split(\\" \\");el.innerHTML=(p[0]+(p.length>1?\\"<br>\\"+p.slice(1).join(\\" \\"): \\"\\")).toUpperCase();}}"',
'    +"function updResult(v){var el=document.querySelector(\\".ach-pos\\");if(el)el.textContent=v;}"',
'    +"function updTourn(v){var el=document.querySelector(\\".ach-tourn\\");if(el)el.textContent=v;}"',
'    +"<"+"/scri"+"pt>"',
'    +"</body></html>";',
'}',
];

const NEW_FN = lines.join('\n');

html = html.slice(0, fnStart) + NEW_FN + html.slice(fnEnd);
fs.writeFileSync(file, html, 'utf8');
console.log('Done.');
